name: IPSE_ML_CH_env
channels:
  - conda-forge
dependencies:
  - python=3.11

  # Core scientific stack
  - numpy
  - pandas
  - scikit-learn

  # ML / models
  - xgboost
  - shap

  # Chemistry / materials
  - pymatgen
  - matminer
  - mendeleev
  - periodictable
  - smact

  # Database / utils
  - pymongo
  - requests

  # Ensure pip available
  - pip

  # Pip-only packages
  - pip:
      - chemformula
