name: IPSE_DB_env
  name: DB
channels:
  - conda-forge
dependencies:
  - python=3.11

  # Core
  - numpy
  - requests
  - pymongo
  - tabulate

  # Materials / chemistry
  - pymatgen

  # Materials Project API
  - mp-api

  # Pip-only / safer via pip
  - pip
  - pip:
      - qmpy_rester
