# Auto-generated from provided CSV (atomic radii)

WC_atomic_radii = {
    'H': {
        'rs': 0.529,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'He': {
        'rs': 0.291,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Li': {
        'rs': 1.586,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Be': {
        'rs': 1.04,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'B': {
        'rs': 0.769,
        'rp': 0.776,
        'rd': None,
        'rf': None,
    },
    'C': {
        'rs': 0.62,
        'rp': 0.596,
        'rd': None,
        'rf': None,
    },
    'N': {
        'rs': 0.521,
        'rp': 0.4875,
        'rd': None,
        'rf': None,
    },
    'O': {
        'rs': 0.45,
        'rp': 0.4135,
        'rd': None,
        'rf': None,
    },
    'F': {
        'rs': 0.396,
        'rp': 0.3595,
        'rd': None,
        'rf': None,
    },
    'Ne': {
        'rs': 0.354,
        'rp': 0.3175,
        'rd': None,
        'rf': None,
    },
    'Na': {
        'rs': 1.713,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Mg': {
        'rs': 1.279,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Al': {
        'rs': 1.044,
        'rp': 1.312,
        'rd': None,
        'rf': None,
    },
    'Si': {
        'rs': 0.904,
        'rp': 1.068,
        'rd': None,
        'rf': None,
    },
    'P': {
        'rs': 0.803,
        'rp': 0.9175,
        'rd': None,
        'rf': None,
    },
    'S': {
        'rs': 0.723,
        'rp': 0.808,
        'rd': None,
        'rf': None,
    },
    'Cl': {
        'rs': 0.66,
        'rp': 0.7235,
        'rd': None,
        'rf': None,
    },
    'Ar': {
        'rs': 0.607,
        'rp': 0.657,
        'rd': None,
        'rf': None,
    },
    'K': {
        'rs': 2.162,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Ca': {
        'rs': 1.69,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Sc': {
        'rs': 1.57,
        'rp': None,
        'rd': 0.539,
        'rf': None,
    },
    'Ti': {
        'rs': 1.477,
        'rp': None,
        'rd': 0.489,
        'rf': None,
    },
    'V': {
        'rs': 1.401,
        'rp': None,
        'rd': 0.449,
        'rf': None,
    },
    'Cr': {
        'rs': 1.453,
        'rp': None,
        'rd': 0.4265,
        'rf': None,
    },
    'Mn': {
        'rs': 1.278,
        'rp': None,
        'rd': 0.3885,
        'rf': None,
    },
    'Fe': {
        'rs': 1.227,
        'rp': None,
        'rd': 0.364,
        'rf': None,
    },
    'Co': {
        'rs': 1.181,
        'rp': None,
        'rd': 0.343,
        'rf': None,
    },
    'Ni': {
        'rs': 1.139,
        'rp': None,
        'rd': 0.324,
        'rf': None,
    },
    'Cu': {
        'rs': 1.191,
        'rp': None,
        'rd': 0.311,
        'rf': None,
    },
    'Zn': {
        'rs': 1.065,
        'rp': None,
        'rd': 0.2925,
        'rf': None,
    },
    'Ga': {
        'rs': 0.96,
        'rp': 1.254,
        'rd': 0.2755,
        'rf': None,
    },
    'Ge': {
        'rs': 0.886,
        'rp': 1.09,
        'rd': 0.2605,
        'rf': None,
    },
    'As': {
        'rs': 0.826,
        'rp': 0.9915,
        'rd': 0.2465,
        'rf': None,
    },
    'Se': {
        'rs': 0.775,
        'rp': 0.909,
        'rd': 0.2345,
        'rf': None,
    },
    'Br': {
        'rs': 0.73,
        'rp': 0.8425,
        'rd': 0.2235,
        'rf': None,
    },
    'Kr': {
        'rs': 0.691,
        'rp': 0.787,
        'rd': 0.2135,
        'rf': None,
    },
    'Rb': {
        'rs': 2.287,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Sr': {
        'rs': 1.836,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Y': {
        'rs': 1.693,
        'rp': None,
        'rd': 0.865,
        'rf': None,
    },
    'Zr': {
        'rs': 1.593,
        'rp': None,
        'rd': 0.79,
        'rf': None,
    },
    'Nb': {
        'rs': 1.589,
        'rp': None,
        'rd': 0.747,
        'rf': None,
    },
    'Mo': {
        'rs': 1.52,
        'rp': None,
        'rd': 0.699,
        'rf': None,
    },
    'Tc': {
        'rs': 1.391,
        'rp': None,
        'rd': 0.645,
        'rf': None,
    },
    'Ru': {
        'rs': 1.41,
        'rp': None,
        'rd': 0.619,
        'rf': None,
    },
    'Rh': {
        'rs': 1.364,
        'rp': None,
        'rd': 0.5865,
        'rf': None,
    },
    'Pd': {
        'rs': 1.32308,
        'rp': None,
        'rd': 0.564,
        'rf': None,
    },
    'Ag': {
        'rs': 1.286,
        'rp': None,
        'rd': 0.533,
        'rf': None,
    },
    'Cd': {
        'rs': 1.184,
        'rp': None,
        'rd': 0.505,
        'rf': None,
    },
    'In': {
        'rs': 1.093,
        'rp': 1.382,
        'rd': 0.4805,
        'rf': None,
    },
    'Sn': {
        'rs': 1.027,
        'rp': 1.24,
        'rd': 0.458,
        'rf': None,
    },
    'Sb': {
        'rs': 0.969,
        'rp': 1.1665,
        'rd': 0.438,
        'rf': None,
    },
    'Te': {
        'rs': 0.92,
        'rp': 1.087,
        'rd': 0.42,
        'rf': None,
    },
    'I': {
        'rs': 0.876,
        'rp': 1.0215,
        'rd': 0.4035,
        'rf': None,
    },
    'Xe': {
        'rs': 0.837,
        'rp': 0.965,
        'rd': 0.388,
        'rf': None,
    },
    'Cs': {
        'rs': 2.518,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Ba': {
        'rs': 2.06,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'La': {
        'rs': 1.915,
        'rp': None,
        'rd': 1.087,
        'rf': None,
    },
    'Ce': {
        'rs': 1.978,
        'rp': None,
        'rd': None,
        'rf': 0.366,
    },
    'Pr': {
        'rs': 1.942,
        'rp': None,
        'rd': None,
        'rf': 0.351,
    },
    'Nd': {
        'rs': 1.912,
        'rp': None,
        'rd': None,
        'rf': 0.337,
    },
    'Pm': {
        'rs': 1.882,
        'rp': None,
        'rd': None,
        'rf': 0.325,
    },
    'Sm': {
        'rs': 1.854,
        'rp': None,
        'rd': None,
        'rf': 0.314,
    },
    'Eu': {
        'rs': 1.826,
        'rp': None,
        'rd': None,
        'rf': 0.3055,
    },
    'Gd': {
        'rs': 1.713,
        'rp': None,
        'rd': 0.96,
        'rf': 0.2925,
    },
    'Tb': {
        'rs': 1.775,
        'rp': None,
        'rd': None,
        'rf': 0.2875,
    },
    'Dy': {
        'rs': 1.75,
        'rp': None,
        'rd': None,
        'rf': 0.279,
    },
    'Ho': {
        'rs': 1.727,
        'rp': None,
        'rd': None,
        'rf': 0.2715,
    },
    'Er': {
        'rs': 1.703,
        'rp': None,
        'rd': None,
        'rf': 0.264,
    },
    'Tm': {
        'rs': 1.681,
        'rp': None,
        'rd': None,
        'rf': 0.2575,
    },
    'Yb': {
        'rs': 1.658,
        'rp': None,
        'rd': None,
        'rf': 0.2515,
    },
    'Lu': {
        'rs': 1.553,
        'rp': None,
        'rd': 0.885,
        'rf': 0.2435,
    },
    'Hf': {
        'rs': 1.476,
        'rp': None,
        'rd': 0.829,
        'rf': None,
    },
    'Ta': {
        'rs': 1.413,
        'rp': None,
        'rd': 0.784,
        'rf': None,
    },
    'W': {
        'rs': 1.36,
        'rp': None,
        'rd': 0.746,
        'rf': None,
    },
    'Re': {
        'rs': 1.31,
        'rp': None,
        'rd': 0.723,
        'rf': None,
    },
    'Os': {
        'rs': 1.266,
        'rp': None,
        'rd': 0.6925,
        'rf': None,
    },
    'Ir': {
        'rs': 1.227,
        'rp': None,
        'rd': 0.6655,
        'rf': None,
    },
    'Pt': {
        'rs': 1.221,
        'rp': None,
        'rd': 0.647,
        'rf': None,
    },
    'Au': {
        'rs': 1.187,
        'rp': None,
        'rd': 0.624,
        'rf': None,
    },
    'Hg': {
        'rs': 1.126,
        'rp': None,
        'rd': 0.598,
        'rf': None,
    },
    'Tl': {
        'rs': 1.06,
        'rp': 1.319,
        'rd': 0.575,
        'rf': None,
    },
    'Pb': {
        'rs': 1.01,
        'rp': 1.215,
        'rd': 0.554,
        'rf': None,
    },
    'Bi': {
        'rs': 0.963,
        'rp': 1.2125,
        'rd': 0.534,
        'rf': None,
    },
    'Po': {
        'rs': 0.923,
        'rp': 1.1385,
        'rd': 0.5165,
        'rf': None,
    },
    'At': {
        'rs': 0.885,
        'rp': 1.0775,
        'rd': 0.5,
        'rf': None,
    },
    'Rn': {
        'rs': 0.851,
        'rp': 1.026,
        'rd': 0.485,
        'rf': None,
    },
    'Fr': {
        'rs': 2.447,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Ra': {
        'rs': 2.042,
        'rp': None,
        'rd': None,
        'rf': None,
    },
    'Ac': {
        'rs': 1.895,
        'rp': None,
        'rd': 1.274,
        'rf': None,
    },
    'Th': {
        'rs': 1.788,
        'rp': None,
        'rd': 1.186,
        'rf': None,
    },
    'Pa': {
        'rs': 1.804,
        'rp': None,
        'rd': 1.198,
        'rf': 0.567,
    },
    'U': {
        'rs': 1.775,
        'rp': None,
        'rd': 1.171,
        'rf': 0.536,
    },
    'Np': {
        'rs': 1.741,
        'rp': None,
        'rd': 1.147,
        'rf': 0.516,
    },
    'Pu': {
        'rs': 1.784,
        'rp': None,
        'rd': None,
        'rf': 0.504,
    },
    'Am': {
        'rs': 1.757,
        'rp': None,
        'rd': None,
        'rf': 0.493,
    },
    'Cm': {
        'rs': 1.657,
        'rp': None,
        'rd': 1.086,
        'rf': 0.4735,
    },
    'Bk': {
        'rs': 1.626,
        'rp': None,
        'rd': 1.071,
        'rf': 0.4595,
    },
    'Cf': {
        'rs': 1.598,
        'rp': None,
        'rd': 1.054,
        'rf': 0.4475,
    },
    'Es': {
        'rs': 1.576,
        'rp': None,
        'rd': 1.037,
        'rf': 0.4355,
    },
    'Fm': {
        'rs': 1.557,
        'rp': None,
        'rd': 1.026,
        'rf': 0.425,
    },
    'Md': {
        'rs': 1.527,
        'rp': None,
        'rd': 1.015,
        'rf': 0.415,
    },
    'No': {
        'rs': 1.581,
        'rp': None,
        'rd': None,
        'rf': 0.4075,
    },
}
